# Generated by Django 5.0.1 on 2025-05-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_alter_user_managers_user_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='locality',
        ),
    ]
